---
driver:
  name: vagrant
  customize:
    cpus: 2
    memory: 2048
  network:
    - - forwarded_port
      - guest: 3000
        host: 3000
        auto_correct: true

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-14.04

suites:
  - name: default
    run_list:
      - recipe[frab]
